<a href="https://colab.research.google.com/github/tripathiosho/ImportantNotebooks/blob/main/Copy_of_NN_Forward_and_backward_Propogation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

!gdown 1dLOPwh01o3k8p_hK633ixhD1ehz6nNWk
df = pd.read_csv("/content/spiral.csv")
df.head()

Downloading...
From: https://drive.google.com/uc?id=1dLOPwh01o3k8p_hK633ixhD1ehz6nNWk
To: /content/spiral.csv
100% 12.9k/12.9k [00:00<00:00, 4.71MB/s]

         x1        x2  y
0  0.000000  0.000000  0
1 -0.000650  0.010080  0
2  0.009809  0.017661  0
3  0.007487  0.029364  0
4 -0.000027  0.040404  0

In [ ]:
df.shape

(300, 3)

In [ ]:
df['y'].value_counts()

y
0    100
1    100
2    100
Name: count, dtype: int64

In [ ]:
df['y'].unique()

array([0, 1, 2])

In [ ]:
# Separating feature and label columns
X = df.iloc[:, :-1].to_numpy()
y = df.iloc[:, -1].to_numpy()

In [ ]:
d= X.shape[1] #dimensions x1, x2

In [ ]:
n= len(df['y'].unique()) #no. of classes
m= X.shape[0] #no. of examples

In [ ]:
w = 0.01 * np.random.randn(d,n)

In [ ]:
d

2

In [ ]:
w

array([[ 0.00846681, -0.01093009,  0.00749218],
       [-0.00905226,  0.00397925, -0.00126758]])

In [ ]:
b=np.zeros((1,n))

In [ ]:
b

array([[0., 0., 0.]])

In [ ]:
z = np.dot(X,w) + b

In [ ]:
z.shape

(300, 3)

In [ ]:
e_z = np.exp(z)
e_z / np.sum(e_z, axis=1, keepdims=True)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33330855, 0.33335654, 0.33333491],
       [0.33331469, 0.33332798, 0.33335733],
       [0.33328237, 0.33336151, 0.33335613],
       [0.33323983, 0.33341551, 0.33334467],
       [0.33323456, 0.33340366, 0.33336178],
       [0.33328096, 0.33331194, 0.3334071 ],
       [0.33323614, 0.33336388, 0.33339998],
       [0.33318637, 0.33342695, 0.33338668],
       [0.33323186, 0.33333595, 0.33343219],
       [0.33318025, 0.33339979, 0.33341997],
       [0.33316868, 0.3334004 , 0.33343092],
       [0.33316616, 0.33338659, 0.33344724],
       [0.3331058 , 0.33346655, 0.33342765],
       [0.33317861, 0.33333261, 0.33348879],
       [0.33325262, 0.33320626, 0.33354112],
       [0.33324188, 0.33320551, 0.33355261],
       [0.33330737, 0.333097  , 0.33359563],
       [0.33322377, 0.33319919, 0.33357705],
       [0.33337585, 0.33297253, 0.33365162],
       [0.3334101 , 0.33291158, 0.33367832],
       [0.33321644, 0.33316101, 0.33362255],
       [0.33334854, 0.33296095, 0.33369051],
       [0.3333109 , 0.33299611, 0.333693  ],
       [0.33344081, 0.33280735, 0.33375185],
       [0.33335473, 0.33290463, 0.33374065],
       [0.3334011 , 0.33282691, 0.33377199],
       [0.33350271, 0.33267982, 0.33381748],
       [0.33368034, 0.33244841, 0.33387125],
       [0.333387  , 0.33279746, 0.33381554],
       [0.33362358, 0.33248141, 0.33389501],
       [0.33370975, 0.3323626 , 0.33392765],
       [0.33398855, 0.33204625, 0.33396519],
       [0.33404044, 0.33197635, 0.33398321],
       [0.33389348, 0.33210431, 0.33400222],
       [0.33398108, 0.3319939 , 0.33402502],
       [0.33430479, 0.33169211, 0.3340031 ],
       [0.33422302, 0.33172687, 0.33405011],
       [0.3341427 , 0.33177543, 0.33408187],
       [0.33417318, 0.33172593, 0.33410089],
       [0.3340494 , 0.33182749, 0.33412311],
       [0.33454074, 0.33141321, 0.33404606],
       [0.33455022, 0.33137398, 0.33407579],
       [0.33441129, 0.3314316 , 0.33415711],
       [0.33452538, 0.33132485, 0.33414977],
       [0.33479664, 0.33127811, 0.33392524],
       [0.33475805, 0.33116868, 0.33407327],
       [0.33467107, 0.33115192, 0.33417701],
       [0.33470802, 0.33110155, 0.33419044],
       [0.33481361, 0.33102952, 0.33415687],
       [0.33444274, 0.33124315, 0.33431412],
       [0.33495386, 0.33094777, 0.33409837],
       [0.33497518, 0.33089515, 0.33412967],
       [0.33481247, 0.33088911, 0.33429842],
       [0.33507047, 0.33082832, 0.33410121],
       [0.33512931, 0.33086126, 0.33400943],
       [0.33515185, 0.33076905, 0.3340791 ],
       [0.33519557, 0.33084367, 0.33396076],
       [0.33521963, 0.3308739 , 0.33390647],
       [0.33522614, 0.33095244, 0.33382142],
       [0.33526852, 0.33087035, 0.33386112],
       [0.3348735 , 0.33186665, 0.33325985],
       [0.33518023, 0.33124131, 0.33357846],
       [0.33533758, 0.33085246, 0.33380996],
       [0.33531708, 0.33097347, 0.33370945],
       [0.33539219, 0.33080404, 0.33380377],
       [0.33524696, 0.33123021, 0.33352283],
       [0.33522291, 0.33131691, 0.33346018],
       [0.33544127, 0.33082585, 0.33373289],
       [0.33549118, 0.33073465, 0.33377418],
       [0.33532678, 0.33118452, 0.33348871],
       [0.33508364, 0.33170852, 0.33320785],
       [0.33548969, 0.33087658, 0.33363372],
       [0.3356065 , 0.33061296, 0.33378054],
       [0.33533133, 0.33129563, 0.33337304],
       [0.33542476, 0.33112834, 0.33344689],
       [0.33523485, 0.33154074, 0.33322441],
       [0.33523131, 0.33157207, 0.33319662],
       [0.33497825, 0.33205788, 0.33296387],
       [0.3351151 , 0.33183448, 0.33305042],
       [0.33502704, 0.3320136 , 0.33295936],
       [0.33546508, 0.33121609, 0.33331883],
       [0.33484288, 0.33237107, 0.33278605],
       [0.33405721, 0.33362934, 0.33231345],
       [0.33391539, 0.33385498, 0.33222963],
       [0.33534631, 0.33154468, 0.33310901],
       [0.33405174, 0.33368705, 0.33226122],
       [0.33454442, 0.33294945, 0.33250613],
       [0.33433327, 0.33329572, 0.33237101],
       [0.33429368, 0.33337323, 0.33233309],
       [0.33385192, 0.33404465, 0.33210344],
       [0.3340409 , 0.33378534, 0.33217376],
       [0.33326239, 0.3348982 , 0.33183941],
       [0.33347008, 0.33463122, 0.3318987 ],
       [0.33371814, 0.33430044, 0.33198142],
       [0.33377261, 0.33423911, 0.33198828],
       [0.33366924, 0.33440164, 0.33192912],
       [0.33391435, 0.33406793, 0.33201772],
       [0.33228375, 0.336238  , 0.33147825],
       [0.33407777, 0.33386227, 0.33205997],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33332641, 0.33335835, 0.33331524],
       [0.33330069, 0.33340532, 0.33329398],
       [0.33333151, 0.33338376, 0.33328473],
       [0.33332806, 0.33340438, 0.33326756],
       [0.33329833, 0.3334589 , 0.33324277],
       [0.33328014, 0.33349784, 0.33322203],
       [0.33324851, 0.33355236, 0.33319913],
       [0.33329441, 0.33351261, 0.33319298],
       [0.33320801, 0.33363356, 0.33315843],
       [0.33326083, 0.33358758, 0.33315159],
       [0.33309178, 0.33379142, 0.3331168 ],
       [0.33311371, 0.33379033, 0.33309596],
       [0.33312037, 0.33380218, 0.33307745],
       [0.33306072, 0.33388308, 0.3330562 ],
       [0.33310615, 0.33385413, 0.33303971],
       [0.33297484, 0.33400618, 0.33301899],
       [0.33302743, 0.33397539, 0.33299718],
       [0.33295141, 0.33407064, 0.33297795],
       [0.3329898 , 0.33405265, 0.33295755],
       [0.33286791, 0.33418969, 0.3329424 ],
       [0.33275767, 0.3342978 , 0.33294452],
       [0.33266037, 0.33437115, 0.33296848],
       [0.33258538, 0.33438638, 0.33302824],
       [0.33274485, 0.33438606, 0.33286909],
       [0.3328491 , 0.33431262, 0.33283828],
       [0.33259198, 0.33454335, 0.33286467],
       [0.33246577, 0.33459098, 0.33294325],
       [0.33274775, 0.33447238, 0.33277987],
       [0.33250694, 0.33468284, 0.33281022],
       [0.33242616, 0.33474769, 0.33282615],
       [0.33237947, 0.33479632, 0.33282421],
       [0.33233986, 0.33484302, 0.33281712],
       [0.33225466, 0.33480299, 0.33294235],
       [0.33224977, 0.33492634, 0.33282389],
       [0.33224944, 0.33498501, 0.33276555],
       [0.33215701, 0.3349476 , 0.33289539],
       [0.33212966, 0.33491102, 0.33295932],
       [0.33209134, 0.33503066, 0.332878  ],
       [0.33206143, 0.33501945, 0.33291913],
       [0.33204526, 0.33519364, 0.33276111],
       [0.33199314, 0.33515829, 0.33284857],
       [0.33203395, 0.33488221, 0.33308384],
       [0.33193237, 0.33518165, 0.33288598],
       [0.33197337, 0.33495249, 0.33307414],
       [0.3318624 , 0.33533677, 0.33280083],
       [0.33186599, 0.33516706, 0.33296695],
       [0.33212557, 0.33450967, 0.33336476],
       [0.33200229, 0.33473561, 0.3332621 ],
       [0.33192041, 0.33488444, 0.33319514],
       [0.33195692, 0.33477259, 0.33327048],
       [0.33193414, 0.33479137, 0.33327449],
       [0.33180721, 0.3350415 , 0.33315129],
       [0.33185389, 0.334903  , 0.3332431 ],
       [0.33204624, 0.33449108, 0.33346268],
       [0.33190225, 0.33474573, 0.33335203],
       [0.33238369, 0.33385718, 0.33375913],
       [0.33205715, 0.33440296, 0.33353989],
       [0.33261762, 0.33344577, 0.33393661],
       [0.33209236, 0.33429688, 0.33361076],
       [0.33201434, 0.3344152 , 0.33357046],
       [0.33227704, 0.33394036, 0.3337826 ],
       [0.33218083, 0.33408305, 0.33373612],
       [0.33226263, 0.33392668, 0.33381069],
       [0.33262132, 0.33333711, 0.33404157],
       [0.332253  , 0.33390526, 0.33384174],
       [0.33310185, 0.33259739, 0.33430076],
       [0.3325093 , 0.33345895, 0.33403174],
       [0.3320195 , 0.3342409 , 0.3337396 ],
       [0.33355639, 0.33193211, 0.33451151],
       [0.33215305, 0.33397718, 0.33386977],
       [0.33228959, 0.33373625, 0.33397416],
       [0.33365574, 0.33175484, 0.33458942],
       [0.33271899, 0.33303844, 0.33424257],
       [0.33278829, 0.33291935, 0.33429236],
       [0.3330536 , 0.33252045, 0.33442595],
       [0.33282641, 0.33283066, 0.33434293],
       [0.33370235, 0.33161403, 0.33468361],
       [0.33328844, 0.33214606, 0.33456549],
       [0.33292193, 0.33264343, 0.33443464],
       [0.33355188, 0.33176108, 0.33468705],
       [0.33338632, 0.33196531, 0.33464837],
       [0.33416354, 0.33096061, 0.33487585],
       [0.33446953, 0.33058819, 0.33494228],
       [0.33426735, 0.33080373, 0.33492892],
       [0.33403141, 0.3310705 , 0.33489808],
       [0.33461931, 0.33036799, 0.3350127 ],
       [0.33332241, 0.33195559, 0.334722  ],
       [0.33462847, 0.33032195, 0.33504958],
       [0.3347837 , 0.33013494, 0.33508136],
       [0.33511224, 0.32977869, 0.33510907],
       [0.33504288, 0.32982772, 0.3351294 ],
       [0.33446438, 0.330437  , 0.33509862],
       [0.33402847, 0.33094211, 0.33502942],
       [0.33475125, 0.33007883, 0.33516992],
       [0.33477328, 0.33003662, 0.3351901 ],
       [0.33539924, 0.32938203, 0.33521873],
       [0.33571995, 0.32908389, 0.33519616],
       [0.33595382, 0.32888855, 0.33515763],
       [0.33641137, 0.32868485, 0.33490378],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33335986, 0.333288  , 0.33335214],
       [0.33338353, 0.33324475, 0.33337172],
       [0.33340033, 0.33320742, 0.33339225],
       [0.33345797, 0.33314493, 0.33339711],
       [0.33349318, 0.33309983, 0.33340699],
       [0.33351617, 0.33305061, 0.33343321],
       [0.33355339, 0.33300418, 0.33344243],
       [0.33358838, 0.33295916, 0.33345246],
       [0.33362683, 0.33292532, 0.33344785],
       [0.33365807, 0.33287462, 0.33346731],
       [0.33368318, 0.33281826, 0.33349856],
       [0.33371098, 0.33276933, 0.33351969],
       [0.33373568, 0.33272085, 0.33354347],
       [0.33379075, 0.33272014, 0.3334891 ],
       [0.33382227, 0.33265228, 0.33352545],
       [0.3338538 , 0.33265292, 0.33349327],
       [0.33388421, 0.33255069, 0.3335651 ],
       [0.33391994, 0.33251556, 0.3335645 ],
       [0.33395311, 0.33251289, 0.33353399],
       [0.333982  , 0.33249392, 0.33352408],
       [0.33400365, 0.33235227, 0.33364408],
       [0.33405249, 0.33235935, 0.33358815],
       [0.33407098, 0.3324046 , 0.33352442],
       [0.33411415, 0.33231239, 0.33357346],
       [0.33408998, 0.33245872, 0.3334513 ],
       [0.3341124 , 0.33244348, 0.33344411],
       [0.33406205, 0.33258903, 0.33334893],
       [0.33423215, 0.33219983, 0.33356802],
       [0.33427052, 0.33213311, 0.33359637],
       [0.33411181, 0.33256975, 0.33331844],
       [0.33430427, 0.33215952, 0.33353621],
       [0.33408463, 0.33267079, 0.33324457],
       [0.33401291, 0.33282165, 0.33316544],
       [0.33380462, 0.33318633, 0.33300905],
       [0.33391254, 0.33303037, 0.33305709],
       [0.33444786, 0.33200804, 0.3335441 ],
       [0.33372243, 0.33336546, 0.33291211],
       [0.33433898, 0.3323271 , 0.33333392],
       [0.33385653, 0.3331922 , 0.33295127],
       [0.33404739, 0.3329008 , 0.33305181],
       [0.33430734, 0.33246349, 0.33322918],
       [0.33391436, 0.33315358, 0.33293205],
       [0.33373877, 0.33344135, 0.33281988],
       [0.33404256, 0.33298352, 0.33297392],
       [0.334037  , 0.33301082, 0.33295218],
       [0.33373939, 0.33349031, 0.3327703 ],
       [0.3337199 , 0.33353584, 0.33274426],
       [0.33367367, 0.33362037, 0.33270596],
       [0.33378981, 0.33346471, 0.33274548],
       [0.33320519, 0.33430361, 0.3324912 ],
       [0.3332414 , 0.33427165, 0.33248695],
       [0.33289429, 0.334732  , 0.33237371],
       [0.3331614 , 0.33440923, 0.33242937],
       [0.33350433, 0.33395999, 0.33253569],
       [0.33316509, 0.33443647, 0.33239844],
       [0.3333069 , 0.33426373, 0.33242938],
       [0.33349269, 0.33402437, 0.33248293],
       [0.33292785, 0.33478895, 0.3322832 ],
       [0.33237953, 0.33544839, 0.33217208],
       [0.33296735, 0.33477183, 0.33226082],
       [0.33242855, 0.33543089, 0.33214057],
       [0.33278035, 0.33503707, 0.33218258],
       [0.3322916 , 0.33561695, 0.33209145],
       [0.33221916, 0.33571269, 0.33206815],
       [0.33310297, 0.33467818, 0.33221886],
       [0.33305053, 0.33476237, 0.33218711],
       [0.33336397, 0.33436183, 0.3322742 ],
       [0.33215779, 0.3358528 , 0.33198942],
       [0.33220642, 0.33581948, 0.3319741 ],
       [0.33270608, 0.33526045, 0.33203347],
       [0.33154824, 0.33648592, 0.33196585],
       [0.33225487, 0.335821  , 0.33192412],
       [0.33130714, 0.33670574, 0.33198713],
       [0.33197409, 0.33615873, 0.33186717],
       [0.33219914, 0.33593668, 0.33186418],
       [0.33127082, 0.33681608, 0.33191309],
       [0.33124383, 0.33686191, 0.33189426],
       [0.330922  , 0.33701995, 0.33205805],
       [0.33142832, 0.33677656, 0.33179513],
       [0.33106367, 0.33705666, 0.33187967],
       [0.33094477, 0.33714246, 0.33191277],
       [0.33069504, 0.33715604, 0.33214891],
       [0.33112964, 0.33710534, 0.33176502],
       [0.33115845, 0.33711172, 0.33172983],
       [0.33058011, 0.33726422, 0.33215567],
       [0.33058258, 0.33736168, 0.33205574],
       [0.33060218, 0.33743915, 0.33195867],
       [0.33047776, 0.33739074, 0.3321315 ],
       [0.3304687 , 0.33748189, 0.33204941],
       [0.33047479, 0.3375656 , 0.33195961],
       [0.33114184, 0.3372982 , 0.33155996],
       [0.33057357, 0.33767492, 0.3317515 ],
       [0.33033069, 0.33765457, 0.33201474],
       [0.33062931, 0.33629984, 0.33307086],
       [0.33033796, 0.33781312, 0.33184892],
       [0.33021514, 0.33775237, 0.33203249],
       [0.33017193, 0.33752138, 0.33230669],
       [0.3301659 , 0.3374138 , 0.33242031],
       [0.3302239 , 0.33712967, 0.33264643]])